/**
 * **図鑑の影の絵の対応表**（項目 id → 絵）。オーナー指示 2026-10-08「図鑑の影のクオリティーが低い。
 * もっとデザインのクオリティーを最高品質にして」。
 *
 * 前は lucide の線の絵を灰色にしていた — 線なので「影」に見えず、鳥・鴿子・麻雀が同じ鳥だった。
 * いまは**塗りの絵の形だけ**を影にする（ポケモン図鑑の「まだ見ていない」影と同じ考え方）。
 *
 * 絵の出どころ（どれも商用可・改変可。`public/licenses/dex-silhouettes.txt`）:
 * - `fe:` Microsoft **Fluent Emoji Flat**（MIT）。色は使わず、輪郭（不透明な所）だけを
 *   なぞって1本の形にする（`scripts/dex-silhouettes/build.ts`）。食べ物・動物・人など。
 * - `mdi:` **Material Design Icons**（Apache-2.0）。絵文字に無い家電・家具など。iOS が
 *   SF Symbols の塗りの記号を使うのと同じ種類の絵。
 * - `ms:` Google **Material Symbols**（Apache-2.0）。上の2つに無い物（水筒・マグなど）。
 * - `cw:` このアプリで描いた形（`scripts/dex-silhouettes/custom.ts`）。どこにも無い物だけ。
 *
 * 決まり: **同じカテゴリーの中では別の絵**（並んだ影が見分けられる）。どうしても同じになる物は
 * `DEX_GLYPH_SHARED` に理由つきで載せる（`dex-glyphs.test.ts` が確かめる）。
 * 絵を足したり変えたりしたら `npx tsx scripts/dex-silhouettes/build.ts` で形を作り直す。
 */

export type DexGlyphRef = `${"fe" | "mdi" | "ms" | "cw"}:${string}`;

// prettier-ignore
export const DEX_GLYPHS: Readonly<Record<string, DexGlyphRef>> = {
  // 1 🧋 飲み物
  bubbletea: "fe:bubble-tea",
  coffee: "fe:hot-beverage",
  tea: "fe:teacup-without-handle",
  juice: "fe:beverage-box",
  water: "ms:water-bottle",
  soymilk: "fe:pouring-liquid",
  milk: "fe:glass-of-milk",
  blacktea: "fe:teapot",
  greentea: "mdi:tea",
  milktea: "fe:cup-with-straw",
  cola: "mdi:bottle-soda-classic",
  latte: "ms:glass-cup",
  soda: "fe:bottle-with-popping-cork",
  sportsdrink: "fe:sake",
  beer: "fe:beer-mug",
  wintermelontea: "fe:tumbler-glass",
  yogurtdrink: "fe:jar",
  hotcocoa: "ms:coffee",
  wine: "fe:wine-glass",

  // 2 🍜 料理・屋台
  rice: "fe:cooked-rice",
  noodles: "fe:spaghetti",
  bento: "fe:bento-box",
  dumplings: "fe:dumpling",
  bun: "fe:moon-cake",
  egg: "fe:egg",
  braisedporkrice: "fe:curry-rice",
  friedrice: "fe:shallow-pan-of-food",
  soup: "fe:pot-of-food",
  beefnoodles: "fe:steaming-bowl",
  danbing: "fe:burrito",
  sandwich: "fe:sandwich",
  tofu: "fe:butter",
  porridge: "fe:bowl-with-spoon",
  friedchicken: "fe:poultry-leg",
  stinkytofu: "fe:falafel",
  hotpot: "fe:fondue",
  scallionpancake: "fe:pancakes",
  hamburger: "fe:hamburger",

  // 3 🍎 果物・野菜
  apple: "fe:red-apple",
  banana: "fe:banana",
  mango: "fe:mango",
  tomato: "fe:tomato",
  cabbage: "fe:leafy-green",
  orange: "fe:tangerine",
  watermelon: "fe:watermelon",
  guava: "fe:pear",
  grapes: "fe:grapes",
  pineapple: "fe:pineapple",
  papaya: "fe:melon",
  carrot: "fe:carrot",
  onion: "fe:onion",
  sweetpotato: "fe:roasted-sweet-potato",
  corn: "fe:ear-of-corn",
  strawberry: "fe:strawberry",
  lemon: "fe:lemon",
  cucumber: "fe:cucumber",
  potato: "fe:potato",

  // 4 🍰 お菓子・パン
  bread: "fe:croissant",
  cake: "fe:birthday-cake",
  cookie: "mdi:cookie",
  icecream: "fe:soft-ice-cream",
  pineapplecake: "fe:moon-cake",
  candy: "fe:candy",
  chocolate: "fe:chocolate-bar",
  toast: "fe:bread",
  shavedice: "fe:shaved-ice",
  chips: "fe:french-fries",
  pudding: "fe:custard",
  douhua: "fe:bowl-with-spoon",
  donut: "fe:doughnut",
  eggtart: "fe:pie",
  mochi: "fe:dango",
  taroballs: "fe:bubbles",
  waffle: "fe:waffle",
  jelly: "fe:ice",
  popcorn: "fe:popcorn",

  // 5 🥢 台所・食器
  cup: "ms:local-cafe",
  bowl: "mdi:bowl",
  chopsticks: "fe:chopsticks",
  plate: "fe:fork-and-knife-with-plate",
  spoon: "fe:spoon",
  fork: "fe:fork-and-knife",
  knife: "fe:kitchen-knife",
  straw: "cw:straw",
  papercup: "mdi:cup-water",
  pot: "mdi:pot",
  fryingpan: "fe:cooking",
  glass: "mdi:glass-water",
  kettle: "mdi:kettle",
  cuttingboard: "cw:cuttingboard",
  bentobox: "mdi:food-takeout-box",
  thermos: "mdi:bottle-tonic",
  wok: "mdi:pot-mix",
  teapot: "fe:teapot",
  sponge: "fe:sponge",
  dishsoap: "fe:lotion-bottle",

  // 6 🛋️ 家の中
  chair: "fe:chair",
  table: "mdi:table-furniture",
  bed: "fe:bed",
  sofa: "mdi:sofa",
  clock: "fe:mantelpiece-clock",
  window: "fe:window",
  door: "fe:door",
  light: "fe:light-bulb",
  desk: "mdi:desk",
  curtain: "mdi:curtains",
  mirror: "fe:mirror",
  pillow: "cw:pillow",
  blanket: "cw:blanket",
  cabinet: "mdi:cupboard",
  lamp: "mdi:desk-lamp",
  bookshelf: "mdi:bookshelf",
  stairs: "mdi:stairs",
  alarmclock: "fe:alarm-clock",
  calendar: "fe:spiral-calendar",

  // 7 🔌 家電
  aircon: "cw:aircon",
  refrigerator: "mdi:fridge",
  tv: "fe:television",
  washingmachine: "mdi:washing-machine",
  fan: "mdi:fan",
  ricecooker: "mdi:pot-steam",
  microwave: "mdi:microwave",
  hairdryer: "mdi:hair-dryer",
  remote: "mdi:remote",
  waterdispenser: "cw:waterdispenser",
  dehumidifier: "mdi:air-humidifier",
  vacuum: "mdi:vacuum",
  hotwaterpot: "mdi:water-boiler",
  oven: "mdi:toaster-oven",
  airpurifier: "ms:air-purifier-gen",
  inductioncooker: "mdi:stove",
  clothesdryer: "mdi:tumble-dryer",
  iron: "mdi:iron",
  toaster: "mdi:toaster",

  // 8 📱 スマホ・電子機器
  phone: "fe:mobile-phone",
  computer: "fe:laptop",
  headphones: "fe:headphone",
  charger: "fe:electric-plug",
  camera: "fe:camera",
  powerbank: "mdi:battery-charging",
  chargingcable: "mdi:cable-data",
  tablet: "mdi:tablet",
  phonecase: "mdi:cellphone",
  battery: "fe:battery",
  keyboard: "fe:keyboard",
  computermouse: "fe:computer-mouse",
  monitor: "fe:desktop-computer",
  speaker: "mdi:speaker",
  usbdrive: "mdi:usb-flash-drive",
  printer: "fe:printer",
  smartwatch: "mdi:watch",
  microphone: "fe:microphone",
  router: "mdi:router-wireless",

  // 9 ✏️ 文房具・本
  book: "fe:closed-book",
  pen: "fe:pen",
  notebook: "fe:notebook",
  scissors: "fe:scissors",
  eraser: "mdi:eraser",
  pencil: "fe:pencil",
  paper: "fe:page-facing-up",
  comic: "fe:open-book",
  ruler: "fe:straight-ruler",
  tape: "mdi:tape",
  pencilcase: "fe:clutch-bag",
  marker: "fe:crayon",
  glue: "cw:glue",
  envelope: "fe:envelope",
  newspaper: "fe:newspaper",
  magazine: "fe:rolled-up-newspaper",
  folder: "fe:file-folder",
  stapler: "cw:stapler",
  paperclip: "fe:paperclip",
  dictionary: "fe:books",

  // 10 🪥 洗面・日用品
  toothbrush: "fe:toothbrush",
  towel: "cw:towel",
  tissue: "fe:roll-of-paper",
  key: "fe:key",
  medicine: "fe:pill",
  money: "fe:dollar-banknote",
  plasticbag: "mdi:shopping",
  toothpaste: "mdi:toothbrush-paste",
  coin: "cw:coin",
  soap: "fe:soap",
  shampoo: "fe:lotion-bottle",
  trashbag: "cw:trashbag",
  transitcard: "fe:identification-card",
  receipt: "fe:receipt",
  toilet: "fe:toilet",
  sink: "mdi:sink",
  wetwipes: "mdi:paper-towels",
  creditcard: "fe:credit-card",
  bandage: "fe:adhesive-bandage",
  hanger: "mdi:hanger",

  // 11 👕 服
  clothes: "fe:womans-clothes",
  pants: "fe:jeans",
  jacket: "fe:coat",
  skirt: "cw:skirt",
  socks: "fe:socks",
  tshirt: "fe:t-shirt",
  shirt: "mdi:tshirt-v",
  shorts: "fe:shorts",
  jeans: "fe:jeans",
  dress: "fe:dress",
  raincoat: "cw:raincoat",
  sweater: "cw:sweater",
  hoodie: "cw:hoodie",
  uniform: "fe:lab-coat",
  pajamas: "cw:pajamas",
  tanktop: "fe:running-shirt",
  underwear: "fe:briefs",
  scarf: "fe:scarf",
  necktie: "fe:necktie",

  // 12 👟 身につける物
  shoes: "fe:mans-shoe",
  hat: "fe:billed-cap",
  glasses: "fe:glasses",
  bag: "fe:handbag",
  umbrella: "fe:closed-umbrella",
  watch: "fe:watch",
  backpack: "fe:backpack",
  mask: "mdi:face-mask",
  slippers: "fe:thong-sandal",
  wallet: "mdi:wallet",
  helmet: "fe:rescue-workers-helmet",
  sneakers: "fe:running-shoe",
  sunglasses: "fe:sunglasses",
  suitcase: "fe:luggage",
  belt: "cw:belt",
  hairtie: "fe:ribbon",
  earrings: "fe:gem-stone",
  necklace: "fe:prayer-beads",
  ring: "fe:ring",
  gloves: "fe:gloves",

  // 13 🛵 乗り物
  scooter: "fe:motor-scooter",
  bus: "fe:bus",
  bicycle: "fe:bicycle",
  mrt: "fe:metro",
  taxi: "fe:taxi",
  car: "fe:automobile",
  train: "fe:train",
  airplane: "fe:airplane",
  truck: "fe:delivery-truck",
  hsr: "fe:high-speed-train",
  boat: "fe:ferry",
  garbagetruck: "fe:articulated-lorry",
  ambulance: "fe:ambulance",
  policecar: "fe:police-car",
  firetruck: "fe:fire-engine",
  kickscooter: "fe:kick-scooter",
  stroller: "mdi:baby-carriage",
  cablecar: "fe:aerial-tramway",

  // 14 🏪 お店・建物
  conveniencestore: "fe:convenience-store",
  temple: "mdi:temple-buddhist",
  school: "fe:school",
  restaurant: "mdi:silverware-fork-knife",
  nightmarket: "fe:red-paper-lantern",
  house: "fe:house",
  building: "fe:office-building",
  breakfastshop: "mdi:food-croissant",
  park: "fe:fountain",
  station: "fe:station",
  hospital: "fe:hospital",
  supermarket: "fe:shopping-cart",
  market: "fe:basket",
  bank: "fe:bank",
  pharmacy: "mdi:pharmacy",
  cafe: "mdi:coffee-maker",
  gasstation: "fe:fuel-pump",
  postoffice: "fe:post-office",
  library: "mdi:library",

  // 15 🚦 街・道
  trafficlight: "mdi:traffic-light",
  signboard: "mdi:sign-direction",
  trashcan: "fe:wastebasket",
  streetlight: "mdi:post-lamp",
  crosswalk: "cw:crosswalk",
  road: "fe:motorway",
  busstop: "fe:bus-stop",
  bench: "mdi:bench-back",
  mailbox: "fe:postbox",
  parkinglot: "mdi:parking",
  bridge: "mdi:bridge",
  vendingmachine: "cw:vendingmachine",
  utilitypole: "cw:utilitypole",
  sidewalk: "mdi:walk",
  flag: "fe:triangular-flag",
  trafficcone: "mdi:traffic-cone",
  firehydrant: "mdi:fire-hydrant",
  atm: "cw:atm",

  // 16 🐾 動物・虫
  dog: "fe:dog",
  cat: "fe:cat",
  bird: "fe:bird",
  fish: "fe:fish",
  rabbit: "fe:rabbit",
  pigeon: "fe:dove",
  sparrow: "fe:blackbird",
  mosquito: "fe:mosquito",
  ant: "fe:ant",
  cockroach: "fe:cockroach",
  gecko: "fe:lizard",
  butterfly: "fe:butterfly",
  chicken: "fe:rooster",
  duck: "fe:duck",
  turtle: "fe:turtle",
  squirrel: "fe:chipmunk",
  frog: "fe:frog",
  hamster: "mdi:rodent",
  ladybug: "fe:lady-beetle",

  // 17 🌿 植物・花
  flower: "fe:tulip",
  tree: "fe:deciduous-tree",
  grass: "mdi:grass",
  leaf: "fe:leaf-fluttering-in-wind",
  pottedplant: "fe:potted-plant",
  banyan: "mdi:tree",
  palmtree: "fe:palm-tree",
  cactus: "fe:cactus",
  rose: "fe:rose",
  bamboo: "fe:pine-decoration",
  sunflower: "fe:sunflower",
  moss: "fe:seedling",
  mushroom: "fe:mushroom",
  cherryblossom: "fe:cherry-blossom",
  orchid: "fe:hibiscus",
  lotus: "fe:lotus",
  seed: "fe:chestnut",

  // 18 ⛅ 自然・空
  sky: "fe:sun-behind-cloud",
  cloud: "fe:cloud",
  mountain: "fe:mountain",
  sea: "fe:water-wave",
  moon: "fe:crescent-moon",
  sun: "fe:sun",
  rain: "fe:cloud-with-rain",
  star: "fe:star",
  river: "mdi:waves",
  rainbow: "fe:rainbow",
  sunset: "mdi:weather-sunset",
  stone: "fe:rock",
  wind: "mdi:weather-windy",
  beach: "fe:umbrella-on-ground",
  lightning: "fe:high-voltage",
  lake: "fe:canoe",
  puddle: "fe:droplet",
  fire: "fe:fire",
  sand: "fe:hourglass-done",

  // 19 ⚽ 遊び・スポーツ
  ball: "mdi:soccer",
  toy: "fe:teddy-bear",
  guitar: "fe:guitar",
  gameconsole: "fe:video-game",
  balloon: "fe:balloon",
  basketball: "mdi:basketball",
  badminton: "fe:badminton",
  baseball: "mdi:baseball",
  tabletennis: "fe:ping-pong",
  clawmachine: "fe:joystick",
  cards: "fe:joker",
  doll: "fe:nesting-dolls",
  puzzle: "fe:puzzle-piece",
  movie: "fe:clapper-board",
  piano: "fe:musical-keyboard",
  skateboard: "fe:skateboard",
  dice: "fe:game-die",
  kite: "fe:kite",

  // 20 🖐️ 体・人
  hand: "fe:raised-hand",
  face: "mdi:emoticon-happy",
  eye: "fe:eye",
  child: "mdi:human-child",
  friend: "fe:busts-in-silhouette",
  mouth: "fe:mouth",
  nose: "fe:nose",
  ear: "fe:ear",
  hair: "fe:person-curly-hair",
  foot: "fe:foot",
  finger: "fe:index-pointing-up",
  head: "fe:bust-in-silhouette",
  mother: "mdi:human-female-girl",
  father: "mdi:human-male-boy",
  baby: "fe:baby",
  student: "fe:student",
  teacher: "mdi:human-male-board",
  grandmother: "mdi:human-cane",
  shopowner: "fe:cook",
};

/**
 * 同じカテゴリーで**わざと同じ絵**にしている組（意味がほぼ同じで、別の絵の方がかえって
 * 嘘になる物）。ここに無い重なりは試験で落ちる。
 */
export const DEX_GLYPH_SHARED: ReadonlyArray<readonly [string, string, string]> = [
  ["pants", "jeans", "褲子と牛仔褲は形が同じズボン"],
];

/** その項目の影の絵（表に無ければ null）。 */
export function dexGlyphOf(id: string): DexGlyphRef | null {
  return DEX_GLYPHS[id] ?? null;
}
