import {
  AirVent,
  AlarmClock,
  Ambulance,
  Apple,
  Archive,
  Armchair,
  Baby,
  Backpack,
  Balloon,
  Banana,
  Bandage,
  Banknote,
  Bath,
  BatteryFull,
  Bean,
  BedDouble,
  Beer,
  Bike,
  Bird,
  Blinds,
  Book,
  BookOpen,
  Bug,
  Building2,
  Bus,
  BusFront,
  Cable,
  CableCar,
  Cake,
  Calendar,
  Camera,
  Candy,
  Car,
  Carrot,
  Cat,
  Citrus,
  Clock,
  Cloud,
  CloudLightning,
  CloudRain,
  CloudSun,
  Coffee,
  Coins,
  Cookie,
  CookingPot,
  CreditCard,
  Croissant,
  Cross,
  CupSoda,
  Dices,
  Dog,
  Donut,
  DoorClosed,
  Droplet,
  Droplets,
  Drumstick,
  Ear,
  Egg,
  Eraser,
  Eye,
  Fan,
  FileText,
  Film,
  Fish,
  Flag,
  Flame,
  Flower,
  Flower2,
  Folder,
  Footprints,
  Fuel,
  Gamepad2,
  Glasses,
  GlassWater,
  GraduationCap,
  Grape,
  Guitar,
  Hamburger,
  Hand,
  Handbag,
  HardHat,
  Headphones,
  Highlighter,
  House,
  IceCreamCone,
  Key,
  Keyboard,
  LampDesk,
  Landmark,
  Laptop,
  Leaf,
  Library,
  Lightbulb,
  Luggage,
  Mail,
  Mailbox,
  Mic,
  Microwave,
  Milk,
  Monitor,
  Moon,
  Motorbike,
  Mountain,
  Mouse,
  Newspaper,
  Notebook,
  Paperclip,
  Pencil,
  Piano,
  Pill,
  Plane,
  Plug,
  Pointer,
  Popcorn,
  Printer,
  Puzzle,
  Rabbit,
  Rainbow,
  Rat,
  Refrigerator,
  Route,
  Router,
  Ruler,
  Sandwich,
  School,
  Scissors,
  Scooter,
  Shirt,
  Ship,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  Signpost,
  Smartphone,
  Smile,
  Sofa,
  Soup,
  Speaker,
  Sprout,
  SquareParking,
  Squirrel,
  Star,
  Store,
  Sun,
  Sunset,
  Tablet,
  ToyBrick,
  Toilet,
  TrafficCone,
  TrainFront,
  TramFront,
  Trash2,
  TreeDeciduous,
  TreePalm,
  Truck,
  Turtle,
  Tv,
  Umbrella,
  UserRound,
  Users,
  Utensils,
  Volleyball,
  Wallet,
  WashingMachine,
  Watch,
  Waves,
  Wind,
  Wine,
  type LucideIcon,
} from "lucide-react";
import type { DexItem } from "@/lib/dex-catalog";

/**
 * **iOS の SF Symbol → Web の絵**（lucide）。SF Symbols は Web では使えないので、近い形の物に
 * 置き換える。近い物が無い名前はここに載せない（角の丸い四角の影になる — iOS の needsArt と同じ）。
 */
export const DEX_SYMBOL_ICONS: Readonly<Record<string, LucideIcon>> = {
  "air.conditioner.horizontal": AirVent,
  "air.purifier": Fan,
  airplane: Plane,
  alarm: AlarmClock,
  ant: Bug,
  applewatch: Watch,
  backpack: Backpack,
  bag: ShoppingBag,
  balloon: Balloon,
  bandage: Bandage,
  banknote: Banknote,
  basket: ShoppingBasket,
  "battery.100": BatteryFull,
  "beach.umbrella": TreePalm,
  "bed.double": BedDouble,
  bicycle: Bike,
  bird: Bird,
  "birthday.cake": Cake,
  "book.closed": Book,
  "books.vertical": Library,
  "building.2": Building2,
  "building.columns": Landmark,
  bus: Bus,
  cabinet: Archive,
  "cable.connector": Cable,
  cablecar: CableCar,
  calendar: Calendar,
  camera: Camera,
  "camera.macro": Flower2,
  car: Car,
  "car.side": Car,
  carrot: Carrot,
  cart: ShoppingCart,
  cat: Cat,
  chair: Armchair,
  clock: Clock,
  cloud: Cloud,
  "cloud.bolt": CloudLightning,
  "cloud.rain": CloudRain,
  "cloud.sun": CloudSun,
  computermouse: Mouse,
  cone: TrafficCone,
  cooktop: CookingPot,
  creditcard: CreditCard,
  cross: Cross,
  "cup.and.heat.waves": Coffee,
  "cup.and.saucer": Coffee,
  "curtains.closed": Blinds,
  dehumidifier: Droplets,
  dice: Dices,
  display: Monitor,
  doc: FileText,
  dog: Dog,
  "door.left.hand.closed": DoorClosed,
  dryer: WashingMachine,
  ear: Ear,
  envelope: Mail,
  eraser: Eraser,
  eye: Eye,
  eyeglasses: Glasses,
  "face.smiling": Smile,
  "fan.desk": Fan,
  ferry: Ship,
  "figure.child": Baby,
  film: Film,
  fish: Fish,
  flag: Flag,
  flame: Flame,
  folder: Folder,
  "fork.knife": Utensils,
  "frying.pan": CookingPot,
  fuelpump: Fuel,
  gamecontroller: Gamepad2,
  guitars: Guitar,
  "hand.point.up": Pointer,
  "hand.raised": Hand,
  handbag: Handbag,
  hare: Rabbit,
  headphones: Headphones,
  helmet: HardHat,
  hifispeaker: Speaker,
  house: House,
  ipad: Tablet,
  iphone: Smartphone,
  jacket: Shirt,
  key: Key,
  keyboard: Keyboard,
  ladybug: Bug,
  "lamp.desk": LampDesk,
  laptopcomputer: Laptop,
  leaf: Leaf,
  lightbulb: Lightbulb,
  magazine: BookOpen,
  mic: Mic,
  microwave: Microwave,
  moon: Moon,
  motorcycle: Motorbike,
  "mountain.2": Mountain,
  mug: Coffee,
  newspaper: Newspaper,
  paperclip: Paperclip,
  parkingsign: SquareParking,
  pencil: Pencil,
  "person.2": Users,
  pianokeys: Piano,
  pills: Pill,
  popcorn: Popcorn,
  powerplug: Plug,
  printer: Printer,
  puzzlepiece: Puzzle,
  rainbow: Rainbow,
  refrigerator: Refrigerator,
  "road.lanes": Route,
  ruler: Ruler,
  scissors: Scissors,
  scooter: Scooter,
  shoe: Footprints,
  "shoe.2": Footprints,
  "signpost.right": Signpost,
  sink: Bath,
  soccerball: Volleyball,
  sofa: Sofa,
  star: Star,
  storefront: Store,
  stroller: Baby,
  "suitcase.rolling": Luggage,
  "sun.horizon": Sunset,
  "sun.max": Sun,
  sunglasses: Glasses,
  teddybear: ToyBrick,
  toilet: Toilet,
  tortoise: Turtle,
  "train.side.front.car": TrainFront,
  "tram.fill.tunnel": TramFront,
  trash: Trash2,
  tree: TreeDeciduous,
  tshirt: Shirt,
  tv: Tv,
  umbrella: Umbrella,
  "wallet.bifold": Wallet,
  washer: WashingMachine,
  "watch.analog": Watch,
  "water.waves": Waves,
  waterbottle: GlassWater,
  "wifi.router": Router,
  wind: Wind,
  wineglass: Wine,
};

/**
 * **Web だけの絵**（iOS では絵がまだ無い物 = needsArt のうち、lucide に分かりやすい形が
 * 在る物）。iOS に AI の影の絵（`dexsil-<id>`）が入るまでの間、Web は角の丸い四角より
 * 何の影か分かる方を出す。表の id で引く（見出し語は言語で変わるので使わない）。
 */
export const DEX_WEB_ITEM_ICONS: Readonly<Record<string, LucideIcon>> = {
  bubbletea: CupSoda,
  juice: CupSoda,
  cola: CupSoda,
  soda: CupSoda,
  milk: Milk,
  beer: Beer,
  egg: Egg,
  soup: Soup,
  sandwich: Sandwich,
  hamburger: Hamburger,
  friedchicken: Drumstick,
  apple: Apple,
  banana: Banana,
  orange: Citrus,
  lemon: Citrus,
  grapes: Grape,
  bread: Croissant,
  cookie: Cookie,
  icecream: IceCreamCone,
  candy: Candy,
  donut: Donut,
  pot: CookingPot,
  glass: GlassWater,
  notebook: Notebook,
  pencil: Pencil,
  dictionary: BookOpen,
  comic: BookOpen,
  marker: Highlighter,
  coin: Coins,
  tshirt: Shirt,
  shirt: Shirt,
  truck: Truck,
  garbagetruck: Truck,
  ambulance: Ambulance,
  school: School,
  library: Library,
  station: TrainFront,
  cafe: Coffee,
  postoffice: Mail,
  pharmacy: Pill,
  temple: Landmark,
  busstop: BusFront,
  mailbox: Mailbox,
  pigeon: Bird,
  sparrow: Bird,
  duck: Bird,
  mosquito: Bug,
  cockroach: Bug,
  squirrel: Squirrel,
  hamster: Rat,
  grass: Sprout,
  pottedplant: Sprout,
  palmtree: TreePalm,
  banyan: TreeDeciduous,
  rose: Flower,
  sunflower: Flower2,
  cherryblossom: Flower,
  orchid: Flower,
  lotus: Flower,
  seed: Bean,
  river: Waves,
  lake: Waves,
  puddle: Droplet,
  baby: Baby,
  foot: Footprints,
  head: UserRound,
  student: GraduationCap,
};

/** その影の絵（無ければ null = 角の丸い四角）。 */
export function dexSilhouetteIcon(item: Pick<DexItem, "id" | "symbol">): LucideIcon | null {
  return (item.symbol && DEX_SYMBOL_ICONS[item.symbol]) || DEX_WEB_ITEM_ICONS[item.id] || null;
}

/**
 * `.sil`: 灰色の影（iOS `DexSilhouette` はマスの 72%）。iOS は塗りの絵なので、Web も線の絵を
 * 同じ灰色で塗りつぶし、線も太めにして「影」に見せる。Web はマスの下に見出し語を重ねるので、
 * 影は少し小さく（64%）上に寄せる。
 */
export function DexSilhouette({ item }: { item: Pick<DexItem, "id" | "symbol"> }) {
  const Icon = dexSilhouetteIcon(item);
  return (
    <span aria-hidden className="dex-sil grid h-[64%] w-[64%] place-items-center">
      {Icon ? (
        <Icon className="h-full w-full" fill="currentColor" strokeWidth={1.6} />
      ) : (
        <span className="block h-[78%] w-[78%] rounded-[22%] bg-current" />
      )}
    </span>
  );
}
